Trevor other
NickHMC/LANL_2019_Clinic pull request #75
Opened 2020-04-26 01:08 UTC by trevor-walker32

Added ReadMe.md

2020-04-26 01:11 UTC, NickHMC requested changes
I think that there may be some changes that you want to look at in template_matcher. I moved it to ImageProcessing/TemplateMatching.

2020-04-26 03:08 UTC, trevor-walker32 reviewed
I already saw these when I merged. Moved template_matcher into ImageProcessing, and flag for writing to original spectrogram data with the new transform or not.

2020-04-26 03:09 UTC, trevor-walker32 reviewed
approve changes

2020-04-30 22:43 UTC, NickHMC approved these changes

2020-04-30 22:43 UTC, merged